import { useEffect, useState } from 'react';
import { Plus, RefreshCw, TrendingUp, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { megalodonClient } from '@/lib/api-client';

export default function EstimacionesPanel({ expedienteId }: { expedienteId: string }) {
  const [data, setData] = useState<any>({ contrato: null, estimaciones: [] }); const [form, setForm] = useState({ numero_estimacion: '1', periodo_inicio: '', periodo_fin: '', monto_ejecutado: '0', avance_fisico: '0', avance_financiero: '0' }); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const load = async () => { try { setData(await megalodonClient.licitacionesObra.estimaciones.list(expedienteId)); } catch (e) { setError((e as Error).message); } };
  useEffect(() => { void load(); }, [expedienteId]);
  const create = async () => { setBusy(true); setError(''); try { await megalodonClient.licitacionesObra.estimaciones.create(expedienteId, { numero_estimacion: Number(form.numero_estimacion), periodo_inicio: form.periodo_inicio || null, periodo_fin: form.periodo_fin || null, monto_ejecutado: Number(form.monto_ejecutado), avance_fisico: Number(form.avance_fisico), avance_financiero: Number(form.avance_financiero) }); await load(); } catch (e) { setError((e as Error).message); } finally { setBusy(false); } };
  return <div className="space-y-6"><header className="flex items-center justify-between"><div><h2 className="text-xl font-bold flex items-center gap-2"><TrendingUp className="w-5 h-5 text-cyan-400" /> Estimaciones de obra</h2><p className="text-sm text-zinc-500">Sólo se muestran entregables realmente persistidos en el contrato.</p></div><button onClick={() => void load()} className="flex items-center gap-2 px-3 py-2 border border-zinc-700 rounded-lg text-sm"><RefreshCw className="w-4 h-4" /> Actualizar</button></header>
    {error && <div className="rounded-lg border border-red-800 bg-red-950/30 p-3 text-sm text-red-300 flex gap-2"><AlertTriangle className="w-4 h-4" />{error}</div>}
    {!data.contrato ? <div className="rounded-xl border border-zinc-800 p-6 text-sm text-zinc-500">No existe contrato.</div> : <><div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 grid grid-cols-3 gap-3 text-sm"><Metric l="Contrato" v={data.contrato.numero_contrato} /><Metric l="Avance físico" v={`${data.contrato.avance_fisico}%`} /><Metric l="Avance financiero" v={`${data.contrato.avance_financiero}%`} /></div><div className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 grid md:grid-cols-3 gap-3"><Field label="Número" value={form.numero_estimacion} onChange={v => setForm({...form, numero_estimacion:v})} type="number" /><Field label="Inicio" value={form.periodo_inicio} onChange={v => setForm({...form, periodo_inicio:v})} type="date" /><Field label="Fin" value={form.periodo_fin} onChange={v => setForm({...form, periodo_fin:v})} type="date" /><Field label="Monto ejecutado" value={form.monto_ejecutado} onChange={v => setForm({...form, monto_ejecutado:v})} type="number" /><Field label="Avance físico" value={form.avance_fisico} onChange={v => setForm({...form, avance_fisico:v})} type="number" /><Field label="Avance financiero" value={form.avance_financiero} onChange={v => setForm({...form, avance_financiero:v})} type="number" /><button disabled={busy || data.contrato.estado !== 'VIGENTE'} onClick={() => void create()} className="md:col-span-3 flex items-center justify-center gap-2 px-4 py-2 rounded-lg bg-cyan-500/20 border border-cyan-500/30 text-cyan-300 disabled:opacity-40"><Plus className="w-4 h-4" /> Registrar estimación</button></div><div className="space-y-2">{data.estimaciones.map((e:any) => <div key={e.id} className="rounded-xl border border-zinc-800 bg-zinc-900/40 p-4 flex items-center justify-between"><div><b>Estimación {e.numero_estimacion}</b><div className="text-xs text-zinc-500">{e.periodo_inicio || '—'} → {e.periodo_fin || '—'}</div></div><div className="flex items-center gap-5 text-sm"><span>${Number(e.monto_ejecutado).toLocaleString()}</span><span>{e.avance_fisico}% físico</span>{e.aprobado ? <span className="text-emerald-400"><CheckCircle2 className="inline w-4 h-4 mr-1"/>Aprobada</span> : <button disabled={busy || data.contrato.estado !== 'VIGENTE'} onClick={async () => { setBusy(true); setError(''); try { await megalodonClient.contratos.entregables.aprobar(data.contrato.id, e.id); await load(); } catch (err) { setError((err as Error).message); } finally { setBusy(false); } }} className="text-amber-300 hover:text-amber-200 disabled:opacity-40">Aprobar</button>}</div></div>)}</div></>}
  </div>;
}
function Field({label,value,onChange,type='text'}:{label:string;value:string;onChange:(v:string)=>void;type?:string}){return <div><label className="text-xs text-zinc-500">{label}</label><input type={type} value={value} onChange={e=>onChange(e.target.value)} className="mt-1 w-full rounded-lg bg-zinc-950 border border-zinc-800 px-3 py-2 text-sm"/></div>}
function Metric({l,v}:{l:string;v:string}){return <div><div className="text-xs text-zinc-500">{l}</div><div className="font-semibold text-zinc-200 mt-1">{v}</div></div>}
