"""Incrementally harden V7 rule-execution provenance and tenant integrity.

The immediately preceding provenance migration creates the first forensic
record shape. This revision evolves that table in-place rather than recreating
it, then adds tenant-consistent composite foreign keys and lifecycle checks.
That preserves upgrade continuity for databases already at the P0 closure
revision.
"""
from alembic import op
import sqlalchemy as sa
from app.db.types import JSONB

revision = "20260826_rule_execution_tenant_hardening"
down_revision = "20260826_tender_rule_execution_provenance"
branch_labels = None
depends_on = None


def _drop_single_column_fk(table: str, column: str) -> None:
    """Drop the old global FK for *column*, whatever autogenerated name it has."""
    bind = op.get_bind()
    row = bind.execute(
        sa.text(
            """
            SELECT c.conname
            FROM pg_constraint c
            JOIN pg_class t ON t.oid = c.conrelid
            JOIN pg_attribute a ON a.attrelid = c.conrelid AND a.attnum = ANY(c.conkey)
            WHERE t.relname = :table
              AND c.contype = 'f'
              AND array_length(c.conkey, 1) = 1
              AND a.attname = :column
            LIMIT 1
            """
        ),
        {"table": table, "column": column},
    ).first()
    if row is not None:
        constraint = row[0].replace('"', '""')
        op.execute(sa.text(f'ALTER TABLE "{table}" DROP CONSTRAINT "{constraint}"'))


def _assert_no_cross_tenant_mismatches() -> None:
    checks = {
        "tender_rule_definitions.tender_id": """
            SELECT 1 FROM tender_rule_definitions r
            JOIN tender_packages t ON t.id = r.tender_id
            WHERE r.tenant_id <> t.tenant_id LIMIT 1
        """,
        "tender_rule_definitions.requirement_id": """
            SELECT 1 FROM tender_rule_definitions r
            JOIN tender_requirements q ON q.id = r.requirement_id
            WHERE r.tenant_id <> q.tenant_id LIMIT 1
        """,
        "tender_validation_runs.tender_id": """
            SELECT 1 FROM tender_validation_runs v
            JOIN tender_packages t ON t.id = v.tender_id
            WHERE v.tenant_id <> t.tenant_id LIMIT 1
        """,
        "tender_validation_evidence_links.validation_run_id": """
            SELECT 1 FROM tender_validation_evidence_links l
            JOIN tender_validation_runs v ON v.id = l.validation_run_id
            WHERE l.tenant_id <> v.tenant_id LIMIT 1
        """,
        "tender_validation_evidence_links.evidence_id": """
            SELECT 1 FROM tender_validation_evidence_links l
            JOIN tender_evidence e ON e.id = l.evidence_id
            WHERE l.tenant_id <> e.tenant_id LIMIT 1
        """,
        "tender_rule_executions.tender_id": """
            SELECT 1 FROM tender_rule_executions x
            JOIN tender_packages t ON t.id = x.tender_id
            WHERE x.tenant_id <> t.tenant_id LIMIT 1
        """,
        "tender_rule_executions.requirement_id": """
            SELECT 1 FROM tender_rule_executions x
            JOIN tender_requirements q ON q.id = x.requirement_id
            WHERE x.tenant_id <> q.tenant_id LIMIT 1
        """,
        "tender_rule_executions.rule_definition_id": """
            SELECT 1 FROM tender_rule_executions x
            JOIN tender_rule_definitions r ON r.id = x.rule_definition_id
            WHERE x.rule_definition_id IS NOT NULL AND x.tenant_id <> r.tenant_id LIMIT 1
        """,
        "tender_rule_executions.validation_run_id": """
            SELECT 1 FROM tender_rule_executions x
            JOIN tender_validation_runs v ON v.id = x.validation_run_id
            WHERE x.validation_run_id IS NOT NULL AND x.tenant_id <> v.tenant_id LIMIT 1
        """,
    }
    bind = op.get_bind()
    for name, sql in checks.items():
        if bind.execute(sa.text(sql)).first() is not None:
            raise RuntimeError(
                f"No se puede aplicar tenant hardening: existe relación cruzada de tenant en {name}."
            )


def upgrade() -> None:
    # Make existing active definitions obey the test gate before the DB CHECKs.
    op.execute(
        sa.text(
            "UPDATE tender_rule_definitions "
            "SET status = 'DRAFT', activated_at = NULL "
            "WHERE status = 'ACTIVE' AND "
            "(COALESCE(jsonb_array_length(test_cases), 0) = 0 OR compiled_hash IS NULL)"
        )
    )
    op.create_check_constraint(
        "ck_tender_rule_active_requires_tests",
        "tender_rule_definitions",
        "status <> 'ACTIVE' OR COALESCE(jsonb_array_length(test_cases), 0) > 0",
    )
    op.create_check_constraint(
        "ck_tender_rule_active_requires_hash",
        "tender_rule_definitions",
        "status <> 'ACTIVE' OR compiled_hash IS NOT NULL",
    )

    # The provenance migration did not yet carry requirement_id, while the
    # canonical model and this hardening revision require the execution to be
    # tenant-linked to its concrete TenderRequirement. Add it before any
    # tenant-consistency query/FK references it, then backfill deterministically
    # from the rule definition that already owns the requirement.
    bind = op.get_bind()
    existing_columns = {row[0] for row in bind.execute(sa.text(
        "SELECT column_name FROM information_schema.columns "
        "WHERE table_schema = current_schema() AND table_name = 'tender_rule_executions'"
    )).all()}
    if "requirement_id" not in existing_columns:
        op.add_column(
            "tender_rule_executions",
            sa.Column("requirement_id", sa.UUID(), nullable=True),
        )

    op.execute(
        sa.text(
            """
            UPDATE tender_rule_executions x
            SET requirement_id = r.requirement_id
            FROM tender_rule_definitions r
            WHERE r.id = x.rule_definition_id
              AND x.requirement_id IS NULL
            """
        )
    )
    missing_requirement = bind.execute(
        sa.text(
            "SELECT 1 FROM tender_rule_executions "
            "WHERE requirement_id IS NULL LIMIT 1"
        )
    ).first()
    if missing_requirement is not None:
        raise RuntimeError(
            "No se puede aplicar tenant hardening: existen ejecuciones sin requirement_id "
            "y no fue posible reconstruir la relación desde tender_rule_definitions."
        )
    op.alter_column("tender_rule_executions", "requirement_id", nullable=False)

    # The closure migration created a lean provenance table. Evolve it in place
    # so an existing closure DB and a fresh chain end at the same schema.
    op.alter_column("tender_rule_executions", "rule_definition_id", nullable=True)
    op.alter_column("tender_rule_executions", "rule_version", nullable=True)
    op.alter_column("tender_rule_executions", "compiled_hash", nullable=True)
    op.alter_column("tender_rule_executions", "hit_policy", nullable=True)

    op.alter_column("tender_rule_executions", "input_snapshot_hash", new_column_name="input_facts_hash")
    op.alter_column("tender_rule_executions", "result", new_column_name="result_payload")
    op.alter_column("tender_rule_executions", "status", new_column_name="execution_status")

    op.add_column("tender_rule_executions", sa.Column("rule_code", sa.String(120), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("source_reference", JSONB(), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("engine_version", sa.String(120), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("matched", sa.Boolean(), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("input_facts", JSONB(), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("actions", JSONB(), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("error_code", sa.String(120), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("revision", sa.Integer(), nullable=True))
    op.add_column("tender_rule_executions", sa.Column("executed_at", sa.String(40), nullable=True))

    op.execute(
        sa.text(
            """
            UPDATE tender_rule_executions x
            SET rule_code = r.code,
                source_reference = COALESCE(r.source_reference, '{}'::jsonb),
                engine_version = 'procurement-rules-v1-migrated',
                matched = NULLIF(x.result_payload ->> 'matched', '')::boolean,
                input_facts = '{}'::jsonb,
                actions = COALESCE(x.result_payload -> 'actions', '[]'::jsonb),
                error_code = NULLIF(x.result_payload ->> 'error', ''),
                revision = COALESCE(v.revision, t.current_revision, 1),
                executed_at = x.created_at::text
            FROM tender_rule_definitions r
            JOIN tender_packages t ON t.id = x.tender_id
            LEFT JOIN tender_validation_runs v ON v.id = x.validation_run_id
            WHERE r.id = x.rule_definition_id
            """
        )
    )

    # Legacy rows should remain explicit rather than silently becoming active
    # under the new required columns.
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET source_reference = '{}'::jsonb WHERE source_reference IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET engine_version = 'procurement-rules-v1-migrated' WHERE engine_version IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET input_facts = '{}'::jsonb WHERE input_facts IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET actions = '[]'::jsonb WHERE actions IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET revision = 1 WHERE revision IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET executed_at = created_at::text WHERE executed_at IS NULL"
    ))
    op.execute(sa.text(
        "UPDATE tender_rule_executions SET rule_code = 'LEGACY_RULE' WHERE rule_code IS NULL"
    ))

    for col in ("rule_code", "source_reference", "engine_version", "input_facts", "actions", "revision", "executed_at"):
        op.alter_column("tender_rule_executions", col, nullable=False)

    _assert_no_cross_tenant_mismatches()

    # Drop the old global parent FKs before replacing them with tenant-aware ones.
    for table, column in (
        ("tender_rule_definitions", "tender_id"),
        ("tender_rule_definitions", "requirement_id"),
        ("tender_validation_runs", "tender_id"),
        ("tender_validation_evidence_links", "validation_run_id"),
        ("tender_validation_evidence_links", "evidence_id"),
        ("tender_rule_executions", "tender_id"),
        ("tender_rule_executions", "requirement_id"),
        ("tender_rule_executions", "rule_definition_id"),
        ("tender_rule_executions", "validation_run_id"),
    ):
        _drop_single_column_fk(table, column)

    for table, name in (
        ("tender_packages", "uq_tender_packages_tenant_id"),
        ("tender_requirements", "uq_tender_requirements_tenant_id"),
        ("tender_evidence", "uq_tender_evidence_tenant_id"),
        ("tender_validation_runs", "uq_tender_validation_runs_tenant_id"),
        ("tender_rule_definitions", "uq_tender_rule_definitions_tenant_id"),
    ):
        op.create_unique_constraint(name, table, ["tenant_id", "id"])

    op.create_foreign_key(
        "fk_tender_rule_def_tenant_tender", "tender_rule_definitions", "tender_packages",
        ["tenant_id", "tender_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_tender_rule_def_tenant_requirement", "tender_rule_definitions", "tender_requirements",
        ["tenant_id", "requirement_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_run_tenant_tender", "tender_validation_runs", "tender_packages",
        ["tenant_id", "tender_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_evidence_link_tenant_validation", "tender_validation_evidence_links", "tender_validation_runs",
        ["tenant_id", "validation_run_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_evidence_link_tenant_evidence", "tender_validation_evidence_links", "tender_evidence",
        ["tenant_id", "evidence_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_rule_execution_tenant_tender", "tender_rule_executions", "tender_packages",
        ["tenant_id", "tender_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_rule_execution_tenant_requirement", "tender_rule_executions", "tender_requirements",
        ["tenant_id", "requirement_id"], ["tenant_id", "id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_rule_execution_tenant_definition", "tender_rule_executions", "tender_rule_definitions",
        ["tenant_id", "rule_definition_id"], ["tenant_id", "id"], ondelete="RESTRICT",
    )
    op.create_foreign_key(
        "fk_rule_execution_tenant_validation", "tender_rule_executions", "tender_validation_runs",
        ["tenant_id", "validation_run_id"], ["tenant_id", "id"], ondelete="RESTRICT",
    )

    op.drop_index("idx_tender_rule_execution_lookup", table_name="tender_rule_executions")
    op.create_index(
        "idx_tender_rule_execution_tenant_requirement_revision",
        "tender_rule_executions", ["tenant_id", "requirement_id", "revision"],
    )
    op.create_index(
        "idx_tender_rule_execution_tenant_hash",
        "tender_rule_executions", ["tenant_id", "compiled_hash"],
    )


def downgrade() -> None:
    op.drop_index("idx_tender_rule_execution_tenant_hash", table_name="tender_rule_executions")
    op.drop_index("idx_tender_rule_execution_tenant_requirement_revision", table_name="tender_rule_executions")
    for name, table in (
        ("fk_rule_execution_tenant_validation", "tender_rule_executions"),
        ("fk_rule_execution_tenant_definition", "tender_rule_executions"),
        ("fk_rule_execution_tenant_requirement", "tender_rule_executions"),
        ("fk_rule_execution_tenant_tender", "tender_rule_executions"),
        ("fk_validation_evidence_link_tenant_evidence", "tender_validation_evidence_links"),
        ("fk_validation_evidence_link_tenant_validation", "tender_validation_evidence_links"),
        ("fk_validation_run_tenant_tender", "tender_validation_runs"),
        ("fk_tender_rule_def_tenant_requirement", "tender_rule_definitions"),
        ("fk_tender_rule_def_tenant_tender", "tender_rule_definitions"),
    ):
        op.drop_constraint(name, table, type_="foreignkey")
    for table, name in (
        ("tender_rule_definitions", "uq_tender_rule_definitions_tenant_id"),
        ("tender_validation_runs", "uq_tender_validation_runs_tenant_id"),
        ("tender_evidence", "uq_tender_evidence_tenant_id"),
        ("tender_requirements", "uq_tender_requirements_tenant_id"),
        ("tender_packages", "uq_tender_packages_tenant_id"),
    ):
        op.drop_constraint(name, table, type_="unique")
    op.create_foreign_key(
        "fk_tender_rule_execution_validation_run_legacy",
        "tender_rule_executions", "tender_validation_runs", ["validation_run_id"], ["id"], ondelete="SET NULL",
    )
    op.create_foreign_key(
        "fk_tender_rule_execution_rule_definition_legacy",
        "tender_rule_executions", "tender_rule_definitions", ["rule_definition_id"], ["id"], ondelete="RESTRICT",
    )
    # requirement_id did not exist in the original provenance revision, so
    # it is intentionally not recreated on downgrade. The compatibility column
    # is removed at the very end after every hardening FK/index is gone.
    op.create_foreign_key(
        "fk_tender_rule_execution_tender_legacy",
        "tender_rule_executions", "tender_packages", ["tender_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_evidence_link_evidence_legacy",
        "tender_validation_evidence_links", "tender_evidence", ["evidence_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_evidence_link_validation_legacy",
        "tender_validation_evidence_links", "tender_validation_runs", ["validation_run_id"], ["id"], ondelete="CASCADE",
    )
    op.create_foreign_key(
        "fk_validation_run_tender_legacy", "tender_validation_runs", "tender_packages", ["tender_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_tender_rule_def_requirement_legacy", "tender_rule_definitions", "tender_requirements", ["requirement_id"], ["id"], ondelete="CASCADE"
    )
    op.create_foreign_key(
        "fk_tender_rule_def_tender_legacy", "tender_rule_definitions", "tender_packages", ["tender_id"], ["id"], ondelete="CASCADE"
    )
    # Reverse the provenance table shape only on downgrade of the hardening
    # revision; dropping the added forensic fields is intentionally avoided for
    # data safety. Alembic can then downgrade the original provenance revision.
    op.create_index("idx_tender_rule_execution_lookup", "tender_rule_executions", ["tenant_id", "tender_id", "rule_definition_id", "created_at"])
    op.drop_column("tender_rule_executions", "executed_at")
    op.drop_column("tender_rule_executions", "revision")
    op.drop_column("tender_rule_executions", "error_code")
    op.drop_column("tender_rule_executions", "actions")
    op.drop_column("tender_rule_executions", "input_facts")
    op.drop_column("tender_rule_executions", "matched")
    op.drop_column("tender_rule_executions", "engine_version")
    op.drop_column("tender_rule_executions", "source_reference")
    op.drop_column("tender_rule_executions", "rule_code")
    op.alter_column("tender_rule_executions", "execution_status", new_column_name="status")
    op.alter_column("tender_rule_executions", "result_payload", new_column_name="result")
    op.alter_column("tender_rule_executions", "input_facts_hash", new_column_name="input_snapshot_hash")
    op.alter_column("tender_rule_executions", "hit_policy", nullable=False)
    op.alter_column("tender_rule_executions", "compiled_hash", nullable=False)
    op.alter_column("tender_rule_executions", "rule_version", nullable=False)
    op.alter_column("tender_rule_executions", "rule_definition_id", nullable=False)
    op.drop_constraint("ck_tender_rule_active_requires_hash", "tender_rule_definitions", type_="check")
    op.drop_constraint("ck_tender_rule_active_requires_tests", "tender_rule_definitions", type_="check")
    op.drop_column("tender_rule_executions", "requirement_id")
